before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/
language: java
env:
  global:
    - secure: "Xyichg6KhhC456oBvQ10c1D/QoR4ANEnkzWlemq6KlvQ7mVPq5YUMRPIXcouQZvXb/JEDtdun0NCLA8OBh9OhfoW9vwnVGYNCALlf7xHYk8OzRHdCkJ3sibpPsJNrJfEMhokgn3/k70elJ3j6DdWE779nwoVqFD8Uo3W2zLDfEM="
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - python asciidoc-8.6.7/asciidoc.py --version
  - dot -V
  
  - echo Hello from DUT INFO Blagnac
  - ls -alF
  
  - echo Creation of OPTI.jar
  - cd sprint_5
  - javac -cp ./src -d ./bin ./src/fr/iut_blagnac/gui/Application.java
  - jar cfm ./build/OPTI.jar ./manifest.txt -C ./bin .
  
  - echo Generation of the Javadoc
  - javadoc -quiet -classpath ./build/lib/junit.jar -d ./doc/html -sourcepath ./src -subpackages fr
  
  - echo Generation of the documentation
  - java -jar ../plantuml.jar -Tpng -o ./srcdoc/images ./srcdoc/diag0.puml
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o ./doc/presentationFinale.html ./srcdoc/presentationFinale.txt
  - python ../asciidoc-8.6.7/asciidoc.py -b slidy -o "./doc/Presentation Finale.html" ./srcdoc/presentationFinale.txt
  - python ../asciidoc-8.6.7/asciidoc.py -o "./doc/Documentation Web.html" ./srcdoc/documentationWeb.adoc
  - python ../asciidoc-8.6.7/asciidoc.py -o "./doc/Documentation Technique.html" "./srcdoc/Documentation Technique.adoc"
  - python ../asciidoc-8.6.7/asciidoc.py -o "./doc/Documentation Utilisateur.html" "./srcdoc/Documentation Utilisateur.adoc"
  
  - echo Compilation of the tests
  - javac -cp ./bin:./build/lib/junit.jar -d ./bin ./src/fr/iut_blagnac/io/CSVManagerTest.java
  - javac -cp ./bin:./build/lib/junit.jar -d ./bin ./src/fr/iut_blagnac/io/OptiElementManagerTest.java
  - javac -cp ./bin:./build/lib/junit.jar -d ./bin ./src/fr/iut_blagnac/util/MakeOptiWebTest.java
 
  - echo Execution of the JUnit tests
  - cp ./build/*.csv ./bin
  - cd ./bin
  - java -cp .:../build/lib/junit.jar fr.iut_blagnac.io.CSVManagerTest
  - java -cp .:../build/lib/junit.jar fr.iut_blagnac.io.OptiElementManagerTest
  - java -cp .:../build/lib/junit.jar fr.iut_blagnac.util.MakeOptiWebTest
  - cd ..

  - echo Execution of the casperJS tests
  - cd test
  - casperjs test casperCredits.js
  - casperjs test casperAccueil.js
  - casperjs test casperEtudiants.js
  - casperjs test casperIntervenants.js
  - casperjs test casperProjets.js
  - casperjs test casperSujets.js
  - cd ..

  - echo Commit to GitHub
  - git clone https://${GIT_NAME}:${GH_TOKEN}@github.com/IUT-Blagnac/MPA2014G1B1.git release
  - git config --global user.email ${GIT_EMAIL}
  - git config --global user.name ${GIT_NAME}
  #- git remote rm origin
  #- git remote add origin https://${GIT_NAME}:${GH_TOKEN}@github.com/IUT-Blagnac/MPA2014G1B1.git
  - cp -R --target-directory=release build
  - cp -R --target-directory=release doc
  - cd release
  - git add build
  - git add doc
  - git commit -m "[skip ci] Commit from Travis-CI"
  - git push origin master